language: python
dist: xenial
matrix:
  include:
  - env: TOXENV=py27
    python: 2.7
  - env: TOXENV=py27-pinned
    python: 2.7
  - env: TOXENV=py27-extra-deps
    python: 2.7
  - env: TOXENV=pypy
    python: 2.7
  - env: TOXENV=pypy3
    python: 3.5
  - env: TOXENV=py35
    python: 3.5
  - env: TOXENV=py35-pinned
    python: 3.5
  - env: TOXENV=py36
    python: 3.6
  - env: TOXENV=py37
    python: 3.7
  - env: TOXENV=py37-extra-deps
    python: 3.7
  - env: TOXENV=docs
    python: 3.6
install:
- "if [ \"$TOXENV\" = \"pypy\" ]; then\n  export PYPY_VERSION=\"pypy-6.0.0-linux_x86_64-portable\"\
  \n  wget \"https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2\"\
  \n  tar -jxf ${PYPY_VERSION}.tar.bz2\n  virtualenv --python=\"$PYPY_VERSION/bin/pypy\"\
  \ \"$HOME/virtualenvs/$PYPY_VERSION\"\n  source \"$HOME/virtualenvs/$PYPY_VERSION/bin/activate\"\
  \nfi\nif [ \"$TOXENV\" = \"pypy3\" ]; then\n  export PYPY_VERSION=\"pypy3.5-5.9-beta-linux_x86_64-portable\"\
  \n  wget \"https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2\"\
  \n  tar -jxf ${PYPY_VERSION}.tar.bz2\n  virtualenv --python=\"$PYPY_VERSION/bin/pypy3\"\
  \ \"$HOME/virtualenvs/$PYPY_VERSION\"\n  source \"$HOME/virtualenvs/$PYPY_VERSION/bin/activate\"\
  \nfi\n"
- pip install -U tox twine wheel codecov
cache:
  directories:
  - $HOME/.cache/pip
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
