language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=jessie
  - python: 3.3
    env: TOXENV=py33
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 2.7
    env: TOXENV=pypy
  - python: 3.6
    env: TOXENV=docs
install:
- "if [ \"$TOXENV\" = \"pypy\" ]; then\n  export PYENV_ROOT=\"$HOME/.pyenv\"\n  if\
  \ [ -f \"$PYENV_ROOT/bin/pyenv\" ]; then\n    pushd \"$PYENV_ROOT\" && git pull\
  \ && popd\n  else\n    rm -rf \"$PYENV_ROOT\" && git clone --depth 1 https://github.com/yyuu/pyenv.git\
  \ \"$PYENV_ROOT\"\n  fi\n  # get latest PyPy from pyenv directly (thanks to natural\
  \ version sort option -V)\n  export PYPY_VERSION=`\"$PYENV_ROOT/bin/pyenv\" install\
  \ --list |grep -o -E 'pypy-[0-9][\\.0-9]*$' |sort -V |tail -1`\n  \"$PYENV_ROOT/bin/pyenv\"\
  \ install --skip-existing \"$PYPY_VERSION\"\n  virtualenv --python=\"$PYENV_ROOT/versions/$PYPY_VERSION/bin/python\"\
  \ \"$HOME/virtualenvs/$PYPY_VERSION\"\n  source \"$HOME/virtualenvs/$PYPY_VERSION/bin/activate\"\
  \nfi\n"
- pip install -U tox twine wheel codecov
cache:
  directories:
  - $HOME/.cache/pip
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
