language: python
dist: xenial
matrix:
  include:
  - env: TOXENV=security
    python: 3.8
  - env: TOXENV=flake8
    python: 3.8
  - env: TOXENV=pylint
    python: 3.8
  - env: TOXENV=docs
    python: 3.7
  - env: TOXENV=typing
    python: 3.8
  - env: TOXENV=pinned
    python: 3.5.2
  - env: TOXENV=asyncio-pinned
    python: 3.5.2
  - env: TOXENV=pypy3-pinned PYPY_VERSION=3-v5.9.0
  - env: TOXENV=py
    python: 3.5
  - env: TOXENV=asyncio
    python: 3.5
  - env: TOXENV=pypy3 PYPY_VERSION=3.5-v7.0.0
  - env: TOXENV=py
    python: 3.6
  - env: TOXENV=pypy3 PYPY_VERSION=3.6-v7.3.1
  - env: TOXENV=py
    python: 3.7
  - env: TOXENV=py PYPI_RELEASE_JOB=true
    python: 3.8
    dist: bionic
  - env: TOXENV=extra-deps
    python: 3.8
    dist: bionic
  - env: TOXENV=asyncio
    python: 3.8
    dist: bionic
install:
- "if [[ ! -z \"$PYPY_VERSION\" ]]; then\n  export PYPY_VERSION=\"pypy$PYPY_VERSION-linux64\"\
  \n  wget \"https://bitbucket.org/pypy/pypy/downloads/${PYPY_VERSION}.tar.bz2\"\n\
  \  tar -jxf ${PYPY_VERSION}.tar.bz2\n  virtualenv --python=\"$PYPY_VERSION/bin/pypy3\"\
  \ \"$HOME/virtualenvs/$PYPY_VERSION\"\n  source \"$HOME/virtualenvs/$PYPY_VERSION/bin/activate\"\
  \nfi\n"
- pip install -U tox twine wheel codecov
cache:
  directories:
  - $HOME/.cache/pip
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
